package model;
// Generated Jan 26, 2018 10:48:47 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QsolutionComponent generated by hbm2java
 */
@Entity
@Table(name = "qsolution_component", catalog = "test")
public class QsolutionComponent implements java.io.Serializable {

	private Integer qsolutionComponentId;
	private Qsolution qsolution;
	private QuestionItem questionItemByNextItemId;
	private QuestionItem questionItemByCurItemId;

	public QsolutionComponent() {
	}

	public QsolutionComponent(Qsolution qsolution, QuestionItem questionItemByNextItemId,
			QuestionItem questionItemByCurItemId) {
		this.qsolution = qsolution;
		this.questionItemByNextItemId = questionItemByNextItemId;
		this.questionItemByCurItemId = questionItemByCurItemId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "qsolution_component_id", unique = true, nullable = false)
	public Integer getQsolutionComponentId() {
		return this.qsolutionComponentId;
	}

	public void setQsolutionComponentId(Integer qsolutionComponentId) {
		this.qsolutionComponentId = qsolutionComponentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "qsolution_id")
	public Qsolution getQsolution() {
		return this.qsolution;
	}

	public void setQsolution(Qsolution qsolution) {
		this.qsolution = qsolution;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "next_item_id")
	public QuestionItem getQuestionItemByNextItemId() {
		return this.questionItemByNextItemId;
	}

	public void setQuestionItemByNextItemId(QuestionItem questionItemByNextItemId) {
		this.questionItemByNextItemId = questionItemByNextItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cur_item_id")
	public QuestionItem getQuestionItemByCurItemId() {
		return this.questionItemByCurItemId;
	}

	public void setQuestionItemByCurItemId(QuestionItem questionItemByCurItemId) {
		this.questionItemByCurItemId = questionItemByCurItemId;
	}

}
